version: "3.4"

services:
  mythosservice:
    image: mythosservice
    container_name: mythosservice
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010/api
      ONEAUTH_API_KEY: c8c2c469-037b-47f2-abf5-1459842fb128
      ONEAUTH_REALM_ID: 230
      DODO_URL: https://api.ioak.io:8120
      DODO_KEY: a53dc337-a203-4980-bfc8-12f19acddd26
      PORT: 8015
    ports:
      - 8015:8015
    networks:
      ioak-net:
        aliases:
          - mythosservice.docker

networks:
  ioak-net:
    external: true
