import * as Handlebars from "handlebars";
import { cloneDeep } from "lodash";

const _MODEL_NAME_GPT3 = "gpt-3.5-turbo";
const _MODEL_NAME_GPT4 = "gpt-4o";
const _MODEL_NAME = _MODEL_NAME_GPT4;

const _RESUME_PROMPT = {
  model: _MODEL_NAME,
  messages: [
    {
      role: "system",
      content:
        "Generate key points of the resume in JSON format with objects in camelCasing based on the following requirements: Overall Objective: Assist user in generating key points of the resume. Instruction: Generate response in JSON format with the following fields: - name: (Full Name) - overview: (Brief overview or summary) - technicalSkills: (List of relevant technical skills as a map object with subtopics, generated by GPT based on the whole resume. Ensure that the subtopic values are non-repetitive, relevant to the subtopic and different versions of a skill are consolidated under a single name. For example, all versions of any programming language and related sub topics should be listed as programming language.) - domainSkills: (List of domain skills as a map object with subtopics, generated by GPT based on the whole resume) - totalExperience: (In years, mention years at the end) - industryNormalizedExperience: (In years, mention years at the end. Experience normalized for the industry by considering project difficulty and technical achievements) - currentDesignation:(current job title or designation) - standardizedDesignation:(standardized job title or designation) - recentExperience: (In years, mention years at the end) - longestExperience: (In years, mention years at the end) - averageExperiencePerCompany: (In years, mention years at the end) - allProjects: (Provide a list of one-line summaries about the projects as a list of String object mentioning key technologies for each key project) - keyProject: (Describe the key project as a String object in 2-3 lines with technologies included) - keyQuestionsToBeAsked: (Provide two lists of questions. One named as 'technical' containing 5 questions in technical aspects, and two named as 'overall' containing overall resume questions retrieved based on the resume) - education: (Final level of education with grades, as a String) Overall JSON object must be named keyPoints.",
    },
    {
      role: "user",
      content:
        " Resume Data : {{resume}} ",
    },
  ],
  temperature: 1,
  max_tokens: 3071,
  top_p: 1,
  frequency_penalty: 0,
  presence_penalty: 0,
};

export const getResumePrompt = (text: string) => {
  const resumePrompt = cloneDeep(_RESUME_PROMPT);
  resumePrompt.messages[1].content = Handlebars.compile(
      resumePrompt.messages[1].content
  )({resume: text, modelName: _MODEL_NAME });
  return resumePrompt;
};